spring:
  profiles:
    active:
      - dev
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: microservicecloud-config-dev
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: microservicecloud-config-test
