spring:
  profiles:
    active:
      - dev
---
server:
  port: 8003
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-yin-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8004
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-yin-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
